default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 12345678
  host: 127.0.0.1

development:
  <<: *default
  database: ops_todo_development

test:
  <<: *default
  database: ops_todo_test

production:
  <<: *default
  database: ops_todo_production
  username: ops_todo
  password: <%= ENV['OPS_TODO_DATABASE_PASSWORD'] %>
